### PR TITLE
add Kokoro build for the legacy Trampoline service account

### LINKED ISSUE #21: Support legacy trampoline service account
This is for making the migration from trampoline v1 easier.

The service account json file is in trampoline bucket.

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #21

Note: We confirmed that the build failed without mounting the trampoline bucket:
https://source.cloud.google.com/results/invocations/3a05bd19-5a7c-4650-a7e2-a0c4162d96e8/targets

### CODE REVIEW

**Review by chingor13 — COMMENTED** [review]
How much work is this actually saving someone while migrating? What are the next steps for the person migrating?

Should we add a warning suggesting what they should do next?

**Comment by tmatsuo** [comment]
> How much work is this actually saving someone while migrating?

You may save time for spinning up your own Kokoro pool for attaching the service account.

> What are the next steps for the person migrating?

Probably the next step is to spin up a new Kokoro pool and attach a service account, setting the permission. I can add migration guide from trampoline v1 later (or I can add it in this PR if you want).

> Should we add a warning suggesting what they should do next?

Not sure. We can grep `TRAMPOLINE_USE_LEGACY_SERVICE_ACCOUNT` to know who is using this config.

**Review by chingor13 — APPROVED** [review]
Ok, I forgot about the default shared pool. I do think we want to add a migration guide.

**Comment by tmatsuo** [comment]
@chingor13 Thanks, #23 filed

**Pull request merged**
